name: Docker CI/CD

on:
  push:
     branches:
       - main

jobs:
  build:
    runs-on: self-hosted


    steps:
      - name: docker build image
        run: |
          cd /home/wizard/self_hosted_WOL
          docker build -t wakeonlan .
          docker compose up -d      
